server:
  port: 8080
  servlet:
    context-path: /bootcamp


spring :
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://xcppnncusfpowp:da4d6a4c19d0d58f4878c79bef492b6df38507bbaf597002f2d505b265360f24@ec2-34-230-115-172.compute-1.amazonaws.com:5432/d8mdn120sfmvlv
    username: xcppnncusfpowp
    password: da4d6a4c19d0d58f4878c79bef492b6df38507bbaf597002f2d505b265360f24

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none



application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend